name: saiive.live
description: DefiChain and Bitcoin Wallet

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.13.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.1
  intl: ^0.17.0
  path_provider: ^2.0.1
  url_launcher: ^6.0.3

  flutter_dotenv: ^5.0.2
  flutter_config: ^2.0.0
  shared_preferences: ^2.0.5
  package_info_plus  : ^1.0.0
  permission_handler: ^8.3.0

  #cryto libs
  defichaindart: ^3.8.0-prerelease.9
  encrypt : ^5.0.0
  pointycastle: ^3.3.4
  aes_crypt: ^0.1.1
  
  #utils
  sprintf: ^6.0.0 
  logger: ^0.7.0
  logger_flutter_console: ^0.7.1+2
  retry: ^3.1.0 
  tuple: ^2.0.0
  mutex: ^3.0.0
  async: ^2.5.0
  upgrader: ^3.3.1
  in_app_update: ^2.0.0
  group_list_view : ^1.1.1
  azblob: ^2.0.0

  #ui libs
  carousel_slider: ^4.0.0
  flutter_typeahead: ^3.1.1
  auto_size_text: ^3.0.0
  qr_flutter: ^4.0.0
  flutter_qr_reader:
    git: 
      url: git://github.com/saiive/flutter_qr_reader
      ref: master

  flutter_launcher_icons: ^0.9.0
  clipboard_manager: ^0.0.4
  flutter_icons: ^1.1.0
  webview_flutter: ^2.0.7
  wakelock: ^0.5.2
  share_plus: ^3.0.4
  blur: ^3.0.0
  sliding_up_panel: ^2.0.0+1

  # Desktop
  window_size:
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size

  # Dependency Injection
  get_it: ^7.1.3

  # Securley store data in a keystore
  flutter_secure_storage: ^5.0.2

  # Flare for animations
  flare_flutter: ^3.0.0

  # HTTP client
  http: ^0.13.4

  #database
  sembast: ^3.1.0+2
  sqflite: ^2.0.0+3

  # Eventbus
  event_taxi: ^1.0.0

  #Flutter Vibrate
  flutter_vibrate: ^1.3.0

  #appcenter
  flutter_appcenter_bundle: ^3.3.2
  device_info: ^2.0.0

  uuid: ^3.0.5

  # TouchID/FaceID
  local_auth: ^1.1.2
  flutter_screen_lock: 
    git: 
      url: git://github.com/saiive/flutter_screen_lock
      ref: master
  app_tracking_transparency: ^2.0.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  msix: ^2.1.2
  flutter_driver:
    sdk: flutter
  test:

flutter_intl:
  enabled: true


flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/logo_black.jpg
    - assets/logo_white.jpg
    - assets/logo_wh.png
    - assets/logo.png
    - assets/Logo_with_text.png
    - assets/env/.env-Debug
    - assets/env/.env-Prod
    - assets/env/.env-Staging
    - assets/image/
    - assets/demo/auctions.json


msix_config:
  display_name: saiive.live - DeFi Wallet
  publisher_display_name: saiive.live
  publisher: CN=saiive.live
  msix_version: 99.99.99.99
  icons_background_color: "#00ADB5"
  architecture: x64
  # See https://docs.microsoft.com/en-us/windows/uwp/packaging/app-capability-declarations
  capabilities: "internetClient"
  #certificate_path
  #certificate_password
  #identity_name